spring.application.name=school
server.port=8081

spring.datasource.url=jdbc:mysql://174.138.105.54:3306/viru_school?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=viru
spring.datasource.password=Viru@083
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

school.monthlyFee=100

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
