spring.application.name=school
server.port=8081

spring.datasource.url=jdbc:mysql://174.138.105.54:3306/viru_school?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=viru
spring.datasource.password=Viru@083
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

school.monthlyFee=100

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

school.registration.enabled=true
school.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000

r2.endpoint=https://2d7c576253b88b8fce8e5e839036a560.r2.cloudflarestorage.com
r2.bucket=viru-school-private
r2.access-key=1b25861726966bdff83ca12419f2e8e2
r2.secret-key=5d1bf2d87f2f62b1e5e5c3178d35fc2c12b59878c4ce45db6d9587ab98be1a87
r2.prefix=student_prof_pic/
r2.max-upload-kb=600
r2.region=auto
token=BP1QXyrpa6XWSCI58AXOGvAYhqlVDrJDWXJvjwyj
